import{a as L,S as v,i as l}from"./assets/vendor-Cu43xbyG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"55276537-fb8dc5fad44054a48b25df817",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function d(r,o){return(await w.get("/",{params:{q:r,page:o,per_page:15}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".btn-load-more"),S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const o=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:n,comments:h,downloads:b})=>`
        <li class="gallery-item">
            <a href="${a}">
                <img src="${s}" alt="${e}" loading="lazy"/>
            </a>
            <ul class="info">
                <li class="info-item"><b>Likes</b><span>${t}</span></li>
                <li class="info-item"><b>Views</b><span>${n}</span></li>
                <li class="info-item"><b>Comments</b><span>${h}</span></li>
                <li class="info-item"><b>Downloads</b><span>${b}</span></li>
            </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",o),S.refresh()}function q(){f.innerHTML=""}function y(){document.querySelector(".loader").classList.add("visible")}function g(){document.querySelector(".loader").classList.remove("visible")}function $(){m.classList.add("visible")}function c(){m.classList.remove("visible")}const B=document.querySelector(".form"),M=document.querySelector(".btn-load-more");let u="",i=1;c();B.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(o){u=o,i=1,q(),c(),y();try{const s=await d(u,i),a=s.hits;if(a.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a),i*15>=s.totalHits?(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$(),i+=1}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}});M.addEventListener("click",async()=>{y();try{const r=await d(u,i),o=r.hits;p(o);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),i*15>=r.totalHits&&(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),i+=1}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
